In [1]:
import numpy as np
import cupy as cp

ModuleNotFoundError: No module named 'cupy'

In [2]:
def get_w_np(x, t):
    xx = np.dot(x.T, x)
    xx_inv = np.linalg.inv(xx)
    xt = np.dot(x.T, t)
    w = np.dot(xx_inv, xt)
    
    return w

In [3]:
# 一番小さいサイズの行列の準備
N = 10

x = np.random.rand(N, N)
t = np.random.rand(N, 1)
w = get_w_np(x, t)

print(w)

[[ 1.21905126]
 [-9.57469376]
 [-4.71085668]
 [ 2.2018679 ]
 [ 4.75154242]
 [-1.04190331]
 [ 0.33090009]
 [-2.57911227]
 [ 4.78278976]
 [ 9.01228658]]


In [4]:
import time

time_start = time.time()

w = get_w_np(x, t)

time_end = time.time()

elapsed_time = time_end - time_start

print('{:.5f} sec'.format(elapsed_time))

0.00039 sec


In [5]:
times_cpu = []

for N in [10, 100, 1000, 10000]:
    np.random.seed(0)
    x = np.random.rand(N, N)
    t = np.random.rand(N, 1)

    time_start = time.time()

    w = get_w_np(x, t)

    time_end = time.time()

    elapsed_time = time_end - time_start
    
    print('N={:>5}:{:8.5f} sec'.format(N, elapsed_time))
    
    times_cpu.append(elapsed_time)

N=   10: 0.00250 sec
N=  100: 0.04500 sec
N= 1000: 0.07155 sec
N=10000:19.98860 sec


In [6]:
# Cupyでは
def get_w_cp(x, t):
    xx = cp.dot(x.T, x)
    xx_inv = cp.linalg.inv(xx)
    xt = cp.dot(x.T, t)
    w = cp.dot(xx_inv, xt)
    
    return w

In [7]:
# NumPy を用いた乱数生成
N = 10
x_np = np.random.rand(N, N)
t_np = np.random.rand(N, 1)

# NumPy の ndarray から CuPy の ndarray へ変換
x_cp = cp.asarray(x_np)
t_cp = cp.asarray(t_np)

In [8]:
# Numpy
w_np = get_w_np(x_np, t_np)

# Cupy
w_cp = get_w_cp(x_cp, t_cp)

print('NumPy:\n', w_np)
print('\nCuPy:\n', w_cp)

NumPy:
 [[ 3.10913241]
 [-4.32028319]
 [ 1.09894125]
 [ 1.63321226]
 [ 1.25977854]
 [-0.89789306]
 [-0.87023945]
 [ 1.09654016]
 [ 1.19753311]
 [-1.3647516 ]]

CuPy:
 [[ 3.10913241]
 [-4.32028319]
 [ 1.09894125]
 [ 1.63321226]
 [ 1.25977854]
 [-0.89789306]
 [-0.87023945]
 [ 1.09654016]
 [ 1.19753311]
 [-1.3647516 ]]


In [9]:
x_cpu= np.zeros((10, 10))
x_gpu=cp.asarray(x_cpu) # copy CPU to GPU
x_cpu= cp.asnumpy(x_gpu) # copy GPU to CPU
print(x_gpu** 2) # square on GPU by basic math
xp=cp.get_array_module(x_gpu) # get `np` or `cp`print(xp.square(x_gpu))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
